version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - default
    container_name: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

    
    
  app:
    environment:
      - HOST=127.0.0.1
      - PORT=3000
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - default
volumes:
  redis-data:

networks:
  default: